Proof of concept
SpookySquidward/ECE539-Final-Project pull request #18
Opened 2023-12-13 20:29 UTC by Lcgunn

Goes through all the models with 1,000 lines. It must be in the parent directory to work.

2023-12-13 22:08 UTC, SpookySquidward requested changes
A few more files are included in this pull request than should be, otherwise though everything looks good

2023-12-13 22:08 UTC, SpookySquidward commented on metrics/metrics.py
@frejaz can you confirm that `metrics.py` should indeed be moved into `metrics`? Will this break anything else?

2023-12-13 23:06 UTC, frejaz commented on metrics/metrics.py
I don't think it makes sense to move it - the metrics folder is only for output. You could rename metrics.py if you think it's confusing, since it's also responsible for visualization

2023-12-13 23:07 UTC, frejaz commented on metrics/metrics.py
The way it has been moved now won't break anything,since the dependency has been updated in bow_models.py

2023-12-14 05:04 UTC, SpookySquidward approved these changes

2023-12-14 05:05 UTC, merged